# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id_information', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sensor_mod', models.BooleanField(default=False)),
                ('sensor_sound', models.BooleanField(default=False)),
            ],
        ),
    ]
