# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.TextField(),
        ),
    ]
