# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170409_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
