# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-10 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170409_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.TextField(),
        ),
    ]
