# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170705_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id_crendencial', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('flota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HasEmpleado',
            fields=[
                ('id_hasEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('nombre', models.TextField()),
                ('id_negocio', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.TextField()),
                ('latitud', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id_reloj', models.AutoField(primary_key=True, serialize=False)),
                ('IMEI', models.TextField()),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField()),
                ('sensor_mod', models.BooleanField(default=False)),
                ('sensor_sound', models.BooleanField(default=False)),
                ('id_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='information',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Xbee',
        ),
        migrations.AddField(
            model_name='hasempleado',
            name='id_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Negocio'),
        ),
        migrations.AddField(
            model_name='credencial',
            name='id_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Empleado'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Negocio'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sensor'),
        ),
    ]
