# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170716_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='date',
        ),
    ]
