# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_valores_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
